---------------------------------------
          Unknown local file
---------------------------------------
 - Open simulation
 - OSError("'models/tests/unknown' could not be opened.")

---------------------------------------
          Unknown remote file
---------------------------------------
 - Open simulation
 - OSError("'https://unknown' could not be opened (host unknown not found).")

---------------------------------------
          Invalid local file
---------------------------------------
 - Open simulation
 - Check simulation:
    - Valid: no
    - Issues:
       - Error: the model is underconstrained (i.e. some variables need to be initialised or computed).
 - Initial settings:
    - Ending point: 50.000000
    - Point interval: 0.001000
 - Run simulation [1]
    - Settings:
       - Starting point: 0.000000
       - Ending point: 50.000000
       - Point interval: 0.001000
       - ODE solver: CVODE
       - Initial values:
          - Constants : n/a
          - States : n/a
          - Rates : n/a
          - Algebraic : n/a
 - RuntimeError('std::runtime_error: The simulation has an invalid runtime and cannot therefore be run.')

---------------------------------------
          Invalid remote file
---------------------------------------
 - Open simulation
 - Check simulation:
    - Valid: no
    - Issues:
       - Error: the model is underconstrained (i.e. some variables need to be initialised or computed).
 - Initial settings:
    - Ending point: 50.000000
    - Point interval: 0.001000
 - Run simulation [1]
    - Settings:
       - Starting point: 0.000000
       - Ending point: 50.000000
       - Point interval: 0.001000
       - ODE solver: CVODE
       - Initial values:
          - Constants : n/a
          - States : n/a
          - Rates : n/a
          - Algebraic : n/a
 - RuntimeError('std::runtime_error: The simulation has an invalid runtime and cannot therefore be run.')
